Host: 0.0.0.0
Port: 8080
Debug: false
JwtAuth:
  AccessSecret: 1234567890
  AccessExpire: 604800
Logger:
  ServiceName: PPanel
  Mode: console
  Encoding: plain
  TimeFormat: "2025-01-01 00:00:00.000"
  Path: logs
  Level: debug
  MaxContentLength: 0
  Compress: false
  Stat: true
  KeepDays: 0
  StackCooldownMillis: 100
  MaxBackups: 0
  MaxSize: 0
  Rotation: daily
  FileTimeFormat: 2025-01-01T00:00:00.000Z00:00
MySQL:
  Addr: ppanel-db:3306
  Dbname: ppanel
  Username: ppanel
  Password: ppanelpassword
  Config: charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
  MaxIdleConns: 10
  MaxOpenConns: 10
  SlowThreshold: 1000
Redis:
  Host: ppanel-cache:6379
  Pass:
  DB: 0
Administrator:
  Email: admin@ppanel.dev
  Password: password
